# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=10)),
                ('job_id', models.CharField(max_length=10)),
                ('proposal', models.TextField()),
                ('amt', models.CharField(max_length=4)),
                ('total_amt', models.CharField(max_length=4)),
                ('status', models.CharField(default=0, max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=60)),
                ('bid_num', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=120)),
                ('resume', models.FileField(null=True, upload_to=b'')),
                ('degree', models.FileField(null=True, upload_to=b'')),
                ('permission', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('due_date', models.DateField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('description', models.TextField()),
                ('amt', models.CharField(max_length=4)),
                ('status', models.CharField(default=0, max_length=1)),
                ('got_solution', models.CharField(default=0, max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=10)),
                ('bid_id', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to=b'')),
                ('status', models.CharField(max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
