# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='std_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
