# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171114_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
