# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180106_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('about', models.TextField()),
                ('profile_picture', models.FileField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('about', models.TextField()),
                ('paypal_email', models.CharField(max_length=50)),
                ('profile_picture', models.FileField(null=True, upload_to=b'')),
            ],
        ),
    ]
