# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
