# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_messages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='permission',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
